# Mohamed Jalaly
# Chess Bingo (a set of chess pieces)

c("White King",
  "Black King",
  "White Queen",
  "Black Queen",
  "White Rook #1",
  "White Rook #2",
  "Black Rook #1",
  "Black Rook #2",
  "White Knight #1",
  "White Knight #2",
  "Black Knight #1",
  "Black Knight #2",
  "White Bishop #1",
  "White Bishop #2",
  "Black Bishop #1",
  "Black Bishop #2",
  "White Pawn #1",
  "White Pawn #2",
  "White Pawn #3",
  "White Pawn #4",
  "White Pawn #5",
  "White Pawn #6",
  "White Pawn #7",
  "White Pawn #8",
  "Black Pawn #1",
  "Black Pawn #2",
  "Black Pawn #3",
  "Black Pawn #4",
  "Black Pawn #5",
  "Black Pawn #6",
  "Black Pawn #7",
  "Black Pawn #8")