# William Arnott
# The players listed on the 2022 Detroit Lions roster
# Names taken from: https://en.wikipedia.org/wiki/2022_Detroit_Lions_season#Final_roster
c(
  "Jared Goff",
  "Nate Sudfeld",
  "Jason Cabinda",
  "Justin Jackson",
  "Craig Reynolds",
  "D'Andre Swift",
  "Jamaal Williams",
  "DJ Chark",
  "Kalif Raymond",
  "Josh Reynolds",
  "Amon-Ra St. Brown",
  "Jameson Williams",
  "James Mitchell",
  "Brock Wright",
  "Shane Zylstra",
  "Kayode Awosika",
  "Evan Brown",
  "Taylor Decker",
  "Jonah Jackson",
  "Matt Nelson",
  "Ross Pierschbacher",
  "Frank Ragnow",
  "Penei Sewell",
  "Dan Skipper",
  "Logan Stenberg",
  "Michael Brockers",
  "Isaiah Buggs",
  "John Cominsky",
  "Aidan Hutchinson",
  "Benito Jones",
  "Alim McNeill",
  "Romeo Okwara",
  "Josh Paschal",
  "Alex Anzalone",
  "Derrick Barnes",
  "Chris Board",
  "Austin Bryant",
  "James Houston",
  "Anthony Pittman",
  "Malcolm Rodriguez",
  "Josh Woods",
  "DeShon Elliott",
  "Will Harris",
  "Mike Hughes",
  "Jerry Jacobs",
  "Kerby Joseph",
  "Ifeatu Melifonwu",
  "C.J. Moore",
  "Jeff Okudah",
  "Amani Oruwariye",
  "Michael Badgley",
  "Scott Daly",
  "Jack Fox"
)