#Top 30 Doctor Who Monsters and Villains
#Sian Turner
# From  https://burrunjor.com/2017/11/23/top-30-doctor-who-monsters-and-villains/

c("Light",
  "Zygons",
  "Drashigs",
  "The Beast",
  "The Autons/The Nestene Consciousness",
  "Morbius",
  "Duroc",
  "The Veil",
  "Cheetah People",
  "Midnight Entity",
  "The Ice Warriors",
  "The Black Guardian",
  "Sil",
  "The Mara",
  "The Great Intelligene",
  "The Silurians and The Sea Devils",
  "The Rani",
  "The Flood",
  "Vashta Nerada",
  "The Weeping Angels",
  "Scaroth",
  "Krynoids/ Harrison Chase",
  "Sontarans",
  "Omega",
  "The Master",
  "Cybermen",
  "Davros",
  "The Haemovores",
  "Sutekh",
  "The Daleks")
