## Aim : bingo card proposal for Star Wars
## Author : sqcao-uofg

c(
  "A long time ago in a galaxy far far away...",
  "the Force",
  "Midi-chlorian",
  "Force-Sensitive",
  "Lightsaber",
  "High Republic",
  "Fall of the Republic",
  "The Phantom Menace",
  "Attack of the Clones",
  "Revenge of the Sith",
  "Imperial Era",
  "Solo",
  "Rogue One",
  "A New Hope",
  "The Empire Strikes Back",
  "Return of the Jedi",
  "New Republic Era",
  "Age of Resistance",
  "The Force Awakens",
  "The Last Jedi",
  "The Rise of Skywalker",
  "Obi- Wan Kenobi",
  "Padmé Amidala",
  "Anakin Skywalker",
  "Darth Vader",
  "Qui-Gon jinn",
  "Master Yoda",
  "C-3PO",
  "R2-D2",
  "Count Dooku",
  "Sheev Palpatine",
  "General Grievous",
  "Luke Skywalker",
  "Leia Organa Solo",
  "Han Solo",
  "Chewbacca",
  "Kylo Ren",
  "Rey Skywalker",
  "Finn",
  "Poe Dameron",
  "BB-8"
)

